### ISSUE TITLE
It reloads every single tab I have open simultaneously..

### ISSUE THREAD

**Issue by cloudcalvin** [issammani/unlimited-medium#11]
Why does it reload every single tab that is open when it is installed? 
This is very suspicious behaviour.

**Comment by issammani** [comment]
It has been a while since I worked on this, but I believe this is the code responsible for that. It refreshes the pages so the user doesn't have to :smile: 

https://github.com/issammani/unlimited-medium/blob/b3315302e88d0bc920a42211914b14445bac733d/app/src/js/utils/handlers.js#L5-L13

**Comment by brw** [comment]
wow ok I just came across this because my browser practically froze after I installed this extension. This might sound weird to you but I thought I'd let you know there are quite a few people with a workflow consisting of hundreds of suspended tabs in the background (also known as tab hoarders, commonly people with ADHD from what I've noticed) and they will not have a good time with this.

It's probably better to do as every other extension does and leave the refreshing to the user, or if you absolutely have to refresh only the tabs that you're sure of are Medium ones, but it does feel very suspicious in general so it's probably best not to.

**Comment by issammani** [comment]
> wow ok I just came across this because my browser practically froze after I installed this extension. This might sound weird to you but I thought I'd let you know there are quite a few people with a workflow consisting of hundreds of suspended tabs in the background (also known as tab hoarders, commonly people with ADHD from what I've noticed) and they will not have a good time with this.
> 
> It's probably better to do as every other extension does and leave the refreshing to the user, or if you absolutely have to refresh only the tabs that you're sure of are Medium ones, but it does feel very suspicious in general so it's probably best not to.

Thank you for your comment. Interesting point you brought up. I didn't think about that actually. The assumption was that even in the worst-case people would have ~20 tabs open or so. But the point you mentioned regarding ADHD is valid. 
This behavior originated from people complaining about the extension not working when all they had to do is refresh the page/tab. Thinking about it now, I guess that refreshing only the active tab on click would do trick and that refreshing all the pages is a bit overkill, but I would have to try it out first and see if it delivers the same user experience.
